HealthManager/Controllers/PatientDashboardController.cs
using HealthManager.Models;
using HealthManager.Models.DTO;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace HealthManager.Controllers
{
    [Authorize(Roles = "Patient")]
    public class PatientDashboardController : Controller
    {
        private readonly HealthManagerContext _dbcontext;

        public PatientDashboardController(HealthManagerContext dbcontext)
        {
            _dbcontext = dbcontext;
        }
        public IActionResult Index()
        {
            return View();
        }
        public async Task <IActionResult> MyAppointments()
        {
            /* var userCookie = Request.Cookies["User"];

             if (string.IsNullOrEmpty(userCookie))
             {
                  return RedirectToAction("Login", "Authorize");
             }


             if (!int.TryParse(userCookie, out int patientId))
             {
                 return BadRequest("Invalid cookie value. There is no cookie.");
             }

             var patientAppointments = await _dbcontext.Appointments
                 .Where(p => p.PatientId == patientId && p.Status=="Reserved")
                 .ToListAsync();*/
            DateTime today = DateTime.Now;
            DateOnly todayDate = DateOnly.FromDateTime(today);
            TimeOnly todayhour = TimeOnly.FromDateTime(today);
            var userIdString = User.FindFirst("Id")?.Value;
            int.TryParse(userIdString, out int userIdInt);
            var patientAppointments = await _dbcontext.Appointments
                 .Where(p => p.Status == "Reserved" && p.PatientId == userIdInt && (p.AppointmentDate > todayDate || (p.AppointmentDate == todayDate && p.AppointmentHour > todayhour)))
                 .Include(a => a.Doctor)
                 .ThenInclude(d => d.SpecialtyNavigation)
                 .OrderByDescending(x => x.AppointmentDate)
                 .ThenByDescending(x => x.AppointmentHour)
                 .ToListAsync();
            List<PatientAppointmentsViewModel> appointmentsVm = patientAppointments.Select(x => new PatientAppointmentsViewModel
            {
                AppointmentId = x.AppointmentId,
                DoctorName = x.Doctor.Name + " " + x.Doctor.Surname,
                DoctorSpecialty = x.Doctor.SpecialtyNavigation.SpecialtyName,
                AppointmentDate = x.AppointmentDate,
                AppointmentHour = x.AppointmentHour
            }).ToList();

            return View(appointmentsVm);
        }
        
        [HttpPost]
        public async Task<MethodResponse> CancelAppointment(Guid appointmentId)
        {
            Appointment databaseAppointment = await _dbcontext.Appointments.FindAsync(appointmentId);
            var requestDate = DateOnly.FromDateTime(DateTime.Now);
            TimeOnly requestTime = TimeOnly.FromDateTime(DateTime.Now);

            DateTime date = DateTime.Now;

            if (databaseAppointment.AppointmentDate.CompareTo(requestDate) >= 0 && date < databaseAppointment.AppointmentDate.ToDateTime(databaseAppointment.AppointmentHour))
            {
                databaseAppointment.Status = "Available";
                databaseAppointment.PatientId = null;
                _dbcontext.Appointments.Update(databaseAppointment);
                await _dbcontext.SaveChangesAsync();
                MethodResponse response = new MethodResponse 
                {
                    Success = true,
                    Message = ""
                };
                return response;
            }
            else
            {
                ViewData["CancelError"] = "The appoinment has to be cancelled before the appointment date.";
                MethodResponse response = new MethodResponse
                {
                    Success = false,
                    Message = ""
                };
                return response;
            }
        }
    }
}

HealthManager/Views/Shared/_AdminDashboard.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HealthManager</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HealthManager.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/form.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    <div class="d-flex content">
        <nav class="d-none d-lg-flex flex-column justify-content-end gap-3 mh-100 bg-danger bg-gradient  shadow-sm p-3">
            <ul class="navbar-nav p-3 fs-5 gap-1">
                <li class="nav-item item">
                    <a class="nav-link" asp-area="" asp-controller="Admin" asp-action="EmployeeList">Employees</a>
                </li>
                <li><hr class="hr" /></li>
                <li class="nav-item item">
                    <a class="nav-link" asp-area="" asp-controller="Admin" asp-action="CreateAdmin">Create Admin</a>
                </li>
                <li><hr class="hr" /></li>
                <li class="nav-item item">
                    <a class="nav-link" asp-area="" asp-controller="Admin" asp-action="CreateDoctor">Create Doctor</a>
                </li>
                <li><hr class="hr" /></li>
                <li class="nav-item logout">
                    <a class="nav-link" asp-area="" asp-controller="Authorize" asp-action="Logout">Logout</a>
                </li>
            </ul>
        </nav>

        <div class="z-1 w-50 offcanvas offcanvas-end" id="navbarToggleExternalContent">
            <nav class="d-flex flex-column justify-content-end gap-3 rounded-end mh-100 bg-danger bg-gradient shadow p-3">
                <div class="d-flex justify-content-end d-lg-none offcanvas-header">
                    <button class="btn btn-close" type="button" data-bs-dismiss="offcanvas" data-bs-target="#navbarToggleExternalContent"></button>
                </div>
                <ul class="navbar-nav p-3 fs-5 gap-1 offcanvas-body">
                    <li class="nav-item item">
                        <a class="nav-link" asp-area="" asp-controller="Admin" asp-action="EmployeeList">Employees</a>
                    </li>
                    <li><hr class="hr" /></li>
                    <li class="nav-item item">
                        <a class="nav-link" asp-area="" asp-controller="Admin" asp-action="CreateAdmin">Create Admin</a>
                    </li>
                    <li><hr class="hr" /></li>
                    <li class="nav-item item">
                        <a class="nav-link" asp-area="" asp-controller="Admin" asp-action="CreateDoctor">Create Doctor</a>
                    </li>
                    <li><hr class="hr" /></li>
                    <li class="nav-item logout">
                        <a class="nav-link" asp-area="" asp-controller="Authorize" asp-action="Logout">Logout</a>
                    </li>
                </ul>
            </nav>
        </div>

        <main role="main" class="w-100 flex-grow-1">
            <header class="header d-flex justify-content-center align-items-center navbar-light p-3">
                <p class="text-white text-start text-lg-center fw-bold fs-5 flex-grow-1 m-0">@ViewData["Title"]</p>
                <button class="navbar-toggler d-lg-none text-black text-xxl-center border-0" type="button" data-bs-toggle="offcanvas" data-bs-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </header>
            @RenderBody()
        </main>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>
<style>

    li>a{
        padding-left: 1rem !important;
        color: black !important;
    }
    .item:hover{
        background-color: orange;
        border-radius: .25rem;
    }

    .logout>:hover {
        color: black !important;
        background-color: yellow !important;
        border-radius: 0.3rem !important;
    }

    .divider:hover{
        background-color: none !important;
    }

    .header{
        min-height: 10dvh;
        background-color: darkred;
    }
    .footer{
        height: auto;
    }
    .content{
        height: 100vh !important;

    }

    html, body {
        margin: 0;
        padding: 0;
        overflow-x: hidden;
    }
    main{
        height: 90dvh;
    }
    nav{
        width: 20vw !important;
    }

    @@media (max-width: 540px) {
        nav {
            width: 100% !important;
        }

        .header{
            justify-content: space-between !important;
        }

        #navbarToggleExternalContent, nav {
            height: 100dvh;
        }

        .content {
            justify-content: end !important;
        }

        nav > div > button {
            position: absolute;
            top: 1rem;
            right: 1rem;
        }

        main {
            max-width: 100vw !important
        }
    }
</style>

HealthManager/Views/Shared/_DoctorDashboard.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HealthManager</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HealthManager.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/form.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    <div class="d-flex content w-100">
        <nav class="d-none d-lg-flex flex-column justify-content-end gap-3 mh-100 bg-gradient  shadow-sm p-3">
            <ul class="navbar-nav w-100 p-3 fs-5 gap-1">
                <li class="nav-item item rounded-2">
                    <a class="nav-link" asp-area="" asp-controller="Doctor" asp-action="PatientTodayList">Patient list</a>
                </li>
                <li><hr class="hr" /></li>
                <li class="nav-item item rounded-2">
                    <a class="nav-link" asp-area="" asp-controller="Doctor" asp-action="MedicalRecords">Medical records</a>
                </li>
                <li><hr class="hr" /></li>
                <li class="nav-item logout">
                    <a class="nav-link" asp-area="" asp-controller="Authorize" asp-action="Logout">Logout</a>
                </li>
            </ul>
        </nav>

        <div class="z-1 w-50 offcanvas offcanvas-end" id="navbarToggleExternalContent">
            <nav class="d-flex flex-column justify-content-end gap-3 rounded-end mh-100 bg-success bg-gradient shadow p-3">
                <div class="d-flex justify-content-end d-lg-none offcanvas-header">
                    <button class="btn btn-close" type="button" data-bs-dismiss="offcanvas" data-bs-target="#navbarToggleExternalContent"></button>
                </div>
                <ul class="navbar-nav p-3 fs-5 gap-1 offcanvas-body">
                    <li class="nav-item item">
                        <a class="nav-link" asp-area="" asp-controller="Doctor" asp-action="PatientTodayList">Patient list</a>
                    </li>
                    <li><hr class="hr" /></li>
                    <li class="nav-item item">
                        <a class="nav-link" asp-area="" asp-controller="Doctor" asp-action="MedicalRecords">Medical records</a>
                    </li>
                    <li><hr class="hr" /></li>
                    <li class="nav-item logout">
                        <a class="nav-link" asp-area="" asp-controller="Authorize" asp-action="Logout">Logout</a>
                    </li>
                </ul>
            </nav>
        </div>

        <main role="main" class="w-100 flex-grow-1">
            <header class="header d-flex justify-content-center align-items-center navbar-light p-3">
                <p class="text-white fw-bold fs-5 m-0">@ViewData["Title"]</p>
                <button class="navbar-toggler d-lg-none text-black text-xxl-center border-0" type="button" data-bs-toggle="offcanvas" data-bs-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </header>
            @RenderBody()
        </main>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>
<style>

    li > a {
        padding-left: 1rem !important;
        padding-right: 1rem !important;
        color: black !important;
    }

    .item:hover {
        background-color: lightgreen;
    }

    .logout > :hover {
        color: black !important;
        background-color: lightcoral !important;
        border-radius: 0.3rem !important;
    }

    .divider:hover {
        background-color: none !important;
    }

    .header {
        min-height: 10dvh;
        background-color: darkturquoise;
    }

    .footer {
        height: auto;
    }

    .content {
        height: 100vh !important;
    }

    html, body {
        margin: 0;
        padding: 0;
        overflow-x: hidden;
    }

    nav{
        background-color: mediumturquoise;
        width: 20vw;
    }
    main {
        height: 90dvh;
    }

    @@media (max-width: 540px) {
        nav {
            width: 100% !important;
        }

        .header {
            justify-content: space-between !important;
        }

        #navbarToggleExternalContent, nav {
            height: 100dvh;
        }

        .content {
            justify-content: end !important;
        }

        nav > div > button {
            position: absolute;
            top: 1rem;
            right: 1rem;
        }

        main {
            max-width: 100vw !important
        }
    }
</style>

HealthManager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HealthManager</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HealthManager.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/form.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body class="d-flex flex-column vh-100 mb-0">
    <header class="shadow d-flex flex-column justify-content-center">


        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light">
            <div class="container-fluid d-flex justify-content-between align-items-baseline">
                <a class="navbar-brand w-50" asp-area="" asp-controller="Home" asp-action="Index">HealthManager</a>
                <div class="flex-grow-1 flex-lg-grow-0">
                    <!--<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                    </button> -->
                    <!--navbar-collapse collapse-->
                    @if ((string)@ViewData["Title"] == "Home")
                    {
                        <div class=" d-flex justify-content-between w-100">
                            <!--d-sm-inline-flex  flex-grow-1-->
                            <ul class="navbar-nav d-flex gap-2 w-100 flex-row">

                                <li class="nav-item btn-group">
                                    <button class="btn text-dark border border-2 rounded px-3 register shadow-sm text-center dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        Login
                                    </button>
                                    <ul class="dropdown-menu z-1 position-absolute">
                                        <li><a asp-area="" asp-controller="Authorize" asp-action="Login" class="nav-link text-dark px-1 text-center">Patients</a></li>
                                        <li><a asp-area="" asp-controller="Authorize" asp-action="AdminLogin" class="nav-link text-dark px-1 text-center">Employees</a></li>
                                    </ul>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link text-dark border border-2 rounded px-3 register shadow-sm text-center" asp-area="" asp-controller="Authorize" asp-action="Register">Register</a>
                                </li>
                            </ul>
                        </div>
                    }
                </div>
            </div>
        </nav>
        
    </header>
    <div class="flex-grow-1 d-flex justify-content-center align-items-center">
        <main role="main" class="pb-3 h-75 w-75">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="d-flex flex-column justify-content-start align-items-center gap-1 gap-lg-2 flex-lg-row w-100">
            <div>
                🔗 <a href="https://github.com/tuUsuario/healthmanager" target="_blank">View code on GitHub</a> &nbsp;|&nbsp;
                
            </div>
            <div>
                💼 <a href="https://linkedin.com/in/tuUsuario" target="_blank">Connect on LinkedIn</a> &nbsp;|&nbsp
            </div>
            <div>
                ✉️ <a href="mailto:tumail.com">Contact me via e-mail</a> &nbsp;|&nbsp;
            </div>
            <div>
                ▶️ <em>Want a live walkthrough? Send me a DM!</em>
            </div>
        </div>
        <small>© 2025 Developed by Alan Coiradas</small>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

<style>
    header{
        background-color: #51E6E2;
        min-height: 10dvh;
    }
    footer{
        background-color: #51E6CB;
        position: static !important;
    }
    .login{
        background-color: #37DBA0;
        border-style: solid;
        border-color: #37DBA0 !important;
    }
    .register{
        border-style: solid;
        border-color: #37ABDB !important;
    }
    .register:hover, .login:hover{
            background-color: #37ABDB;
            border-color: #37ABDB !important;
    }

    .dropdown-menu>li>a:hover{
        background-color: aquamarine !important;
    }
    
    footer>div>div>a{
        text-decoration: none;
    }
</style>

HealthManager/Views/Shared/_PatientDashboard.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HealthManager</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HealthManager.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/form.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">


</head>
<body>
    <div class="d-flex content">
        
            <nav class="d-none d-lg-flex flex-column justify-content-end gap-3 rounded-end mh-100 bg-info bg-gradient shadow p-3">
                <ul class="navbar-nav p-3 fs-5 gap-1">
                    <li class="nav-item item rounded-2">
                        <a class="nav-link" asp-area="" asp-controller="Appointment" asp-action="ReserveAppointment">Reservations</a>
                    </li>
                    <li><hr class="hr" /></li>
                    <li class="nav-item item rounded-2">
                        <a class="nav-link" asp-area="" asp-controller="PatientDashboard" asp-action="MyAppointments">My Appointments</a>
                    </li>
                    <li><hr class="hr" /></li>
                    <li class="nav-item logout">
                        <a class="nav-link" asp-area="" asp-controller="Authorize" asp-action="Logout">Logout</a>
                    </li>
                </ul>
            </nav>

        <div class="z-1 w-50 offcanvas offcanvas-end" id="navbarToggleExternalContent">
            <nav class="d-flex flex-column justify-content-end gap-3 rounded-end mh-100 bg-info bg-gradient shadow p-3">
                <div class="d-flex justify-content-end d-lg-none offcanvas-header">
                    <button class="btn btn-close" type="button" data-bs-dismiss="offcanvas" data-bs-target="#navbarToggleExternalContent"></button>
                </div>
                <ul class="navbar-nav p-3 fs-5 gap-1 offcanvas-body">
                    <li class="nav-item item rounded-2">
                        <a class="nav-link" asp-area="" asp-controller="Appointment" asp-action="ReserveAppointment">Reservations</a>
                    </li>
                    <li><hr class="hr" /></li>
                    <li class="nav-item item rounded-2">
                        <a class="nav-link" asp-area="" asp-controller="PatientDashboard" asp-action="MyAppointments">My Appointments</a>
                    </li>
                    <li><hr class="hr" /></li>
                    <li class="nav-item logout">
                        <a class="nav-link" asp-area="" asp-controller="Authorize" asp-action="Logout">Logout</a>
                    </li>
                </ul>
            </nav>
        </div>
        <main role="main" class="w-100">
            <header class="header d-flex justify-content-center align-items-center p-3 navbar-light">
                <h3 class="text-start text-lg-center flex-grow-1">@ViewData["Title"]</h3>
                <button class="navbar-toggler d-lg-none text-black text-xxl-center border-0" type="button" data-bs-toggle="offcanvas" data-bs-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </header>
            @RenderBody()
        </main>
    </div>

    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>
<style>
   
    li>a{
        padding-left: 1rem !important;
        color: black !important;
    }
    .item:hover{
        background-color: aquamarine
    }

    .logout>:hover {
        color: white !important;
        background-color: red !important;
        border-radius: 0.3rem !important;
    }
    
    .divider:hover{
        background-color: none !important;
    }

    .header{
        min-height: 10dvh;
        background-color: aqua;
    }
    .footer{
        height: auto;
    }
    .content{
        height: 100vh !important;

    }
    nav{
        width: 20vw;
    }

    html, body {
        margin: 0;
        padding: 0;
        overflow-x: hidden;
    }
    @@media (max-width: 540px){
        nav{
            width: 100% !important;
            
        }
        #navbarToggleExternalContent, nav{
            height: 100dvh;
        }
        .content{
            justify-content: end !important;
        }
        nav>div>button{
            position: absolute;
            top: 1rem;
            right: 1rem;
        }
        main{
            max-width: 100vw !important
        }
    }
</style>