HealthManager/Controllers/AuthorizeController.cs
using HealthManager.Models;
using HealthManager.Models.DTO;
using HealthManager.Services.Authentication;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting.Server;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.IdentityModel.Tokens.Jwt;
using System.Reflection;
using System.Security.Claims;

namespace HealthManager.Controllers
{
    public class AuthorizeController : Controller
    {
        private readonly HealthManagerContext _dbcontext;
        private readonly IJWTService _jwtservice;
        public AuthorizeController(HealthManagerContext context, IJWTService jwtservice) {
            _dbcontext = context;
            _jwtservice = jwtservice;
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult Login()
        {
            var existingCookie = ControllerContext.HttpContext.Request.Cookies["Token"];
            if (existingCookie != null)
            {
                string role = User.FindFirst(ClaimTypes.Role).Value;
                switch (role)
                {
                    case "Patient":
                        return RedirectToAction("MyAppointments", "PatientDashboard");
                        
                    case "Doctor":
                        return RedirectToAction("PatientTodayList", "Doctor");
                    case "Admin":
                       return RedirectToAction("EmployeeList", "Admin");
                    default:
                        break;
                }
            }
           
            return View();
        }

        [HttpPost]
        public async Task <IActionResult> Login(AuthorizeRequest request)
        {
           if (ModelState.IsValid)
           {
                Patient patientSearch = await _dbcontext.Patients.Where(p => p.Email == request.Email).FirstOrDefaultAsync();
                if (patientSearch == null)
                {
                    ModelState.AddModelError("Email", "Cannot find an account with the provided email.");
                    return View(request);
                }
                if (!BCrypt.Net.BCrypt.Verify(request.Password, patientSearch.Password))
                {
                    ViewData["Credentials"] = "The credentials are invalid. Please try again.";
                    return View(request);
                }
                string createdToken = _jwtservice.GenerateToken(patientSearch.Name, patientSearch.Email, patientSearch.Role, patientSearch.PatientId);
                HttpContext.Response.Cookies.Append("Token", createdToken,
                    new CookieOptions
                    {
                        Path = "/",
                        Expires = DateTime.UtcNow.AddDays(1),
                        HttpOnly = true,
                        Secure = true,
                        IsEssential = true,
                        SameSite = SameSiteMode.None,
                    });
                return RedirectToAction("MyAppointments", "PatientDashboard");
           }  
           else
           {
                ViewData["AuthorizeResult"] = "* There was an error during the process of authentication. We suggest you try again later.";
                return View(request);
           }
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult Register() 
        {
           var existingCookie = ControllerContext.HttpContext.Request.Cookies["Token"];
           if (existingCookie != null)
           {
                string role = User.FindFirst(ClaimTypes.Role).Value;
                switch (role)
                {
                    case "Patient":
                        return RedirectToAction("MyAppointments", "PatientDashboard");

                    case "Doctor":
                        return RedirectToAction("PatientTodayList", "Doctor");
                    case "Admin":
                        return RedirectToAction("EmployeeList", "Admin");
                    default:
                        break;
                }
            }
            return View();
        }

        [HttpPost]
        public async Task <IActionResult> Register(PatientViewModel patientData)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Patient checkPatientExists = _dbcontext.Patients.FirstOrDefault(x => x.Email == patientData.Email);
                    if (checkPatientExists == null)
                    {
                        Patient newPatient = new Patient
                        {
                            Name = patientData.Name,
                            Surname = patientData.Surname,
                            BirthDate = patientData.Birthdate,
                            Email = patientData.Email,
                            Password = BCrypt.Net.BCrypt.HashPassword(patientData.Password),
                            Dni = patientData.Dni,
                            PhoneNumber = patientData.PhoneNumber,
                            Gender = patientData.Gender,
                            Sex = patientData.Sex,
                        };
                        await _dbcontext.Patients.AddAsync(newPatient);
                        await _dbcontext.SaveChangesAsync();
                        return RedirectToAction("Login");

                    }
                    else
                    {
                        ModelState.AddModelError("Email", "* The provided email is already in use.");
                        return View(patientData);
                    }

                }
                //ModelState.AddModelError(string.Empty, "* There are missing or invalid fields on the form.");
                ViewData["ErrorMessage"] = "* There are missing or invalid fields on the form.";
                return View(patientData);
            }
            catch (Exception error)
            {

                ModelState.AddModelError(string.Empty, "* An error occurred while processing your request. Please try again.");
                Console.WriteLine(error);
                return View(patientData);
            }
        }
        public async Task <IActionResult> Logout()
        {
            var token = Request.Cookies["Token"];
            var handler = new JwtSecurityTokenHandler();
            var jwtToken = handler.ReadJwtToken(token);

            var claims = jwtToken.Claims.Select(c => new { c.Type, c.Value }).ToList();
            var role = jwtToken.Claims.FirstOrDefault(c => c.Type == "role")?.Value;

            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

            if(role == "Admin" || role == "Doctor")
            {
                return RedirectToAction("AdminLogin");
            }
            else
            {
                return RedirectToAction("Login");
            }
                
        }

        [AllowAnonymous]
        public IActionResult AdminLogin()
        {
            var Role = User.FindFirst(ClaimTypes.Role)?.Value;
            if (Role == null)
            {
                return View();
            }
            else if(Role == "Admin")
            {
                return RedirectToAction("EmployeeList", "Admin");
            }
            else
            {
                return RedirectToAction("PatientTodayList", "Doctor");
            }
        }

        [HttpPost]
        public async Task<IActionResult> AdminLogin(AuthorizeRequest request)
        {
            Doctor employee = await _dbcontext.Doctors.Where(d => d.Email == request.Email).FirstOrDefaultAsync(); 
            Admin admin = await _dbcontext.Admins.Where(d => d.Email == request.Email).FirstOrDefaultAsync();
            
           if (employee == null && admin != null)
            {
               
                if (BCrypt.Net.BCrypt.Verify(request.Password, admin.Password))
                {
                    string adminToken = _jwtservice.GenerateToken(admin.Name, admin.Email, admin.Role, admin.Id);
                    HttpContext.Response.Cookies.Append("Token", adminToken,
                        new CookieOptions
                        {
                            Path = "/",
                            Expires = DateTime.UtcNow.AddDays(1),
                            HttpOnly = true,
                            Secure = true,
                            IsEssential = true,
                            SameSite = SameSiteMode.None,
                        });
                    return RedirectToAction("CreateAdmin", "Admin");
                    
                }
                else
                {
                    ViewData["Credentials"] = "The credentials are invalid. Please try again.";
                    return View(request);
                }
            } else if (employee != null && admin == null)
            {
                
                if (BCrypt.Net.BCrypt.Verify(request.Password, employee.Password))
                {
                    string employeeToken = _jwtservice.GenerateToken(employee.Name, employee.Email, employee.Role, employee.DoctorId);
                    HttpContext.Response.Cookies.Append("Token", employeeToken,
                        new CookieOptions
                        {
                            Path = "/",
                            Expires = DateTime.UtcNow.AddDays(1),
                            HttpOnly = true,
                            Secure = true,
                            IsEssential = true,
                            SameSite = SameSiteMode.None,
                        });
                    return RedirectToAction("PatientTodayList", "Doctor");
                }
                else
                {
                    ViewData["Credentials"] = "The credentials are invalid. Please try again.";
                    return View(request);
                }

HealthManager/Views/Authorize/AdminLogin.cshtml
@model HealthManager.Models.DTO.AuthorizeRequest;
@{
    ViewBag.Title = "Admin Login";
}

<main>
    <section class="w-100 d-flex justify-content-center align-items-center">
        <form method="post" asp-controller="Authorize" asp-action="AdminLogin" class="d-flex flex-column gap-2">
            <h2>Admin Login</h2>
            <fieldset>
                <div class="d-flex justify-content-between w-100">
                    <label asp-for="Email" class="flex-grow-1">Email</label>
                    <span asp-validation-for="Email" class="text-danger"></span>
                    @if (ViewBag.Credentials != null)
                    {
                        <p class="justify-content-end text-danger">@ViewBag.Credentials</p>
                    }
                </div>
                <input asp-for="Email" id="email" type="email" class="form-control" />
            </fieldset>
            <fieldset>
                <div class="d-flex justify-content-between w-100">
                    <label asp-for="Password" class="flex-grow-1">Password</label>
                    <span asp-validation-for="Password" class="text-danger"></span>
                </div>
                <input asp-for="Password" id="password" type="password" class="form-control" />
            </fieldset>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </section>
</main>

HealthManager/Views/Authorize/Login.cshtml
@model HealthManager.Models.DTO.AuthorizeRequest;
@{
    ViewData["Title"] = "Login";
    
}

<section class="h-100 w-100 d-flex flex-column justify-content-center align-items-center">
    <h2>Login</h2>     
        <form method="post" asp-controller="Authorize" asp-action="Login" class="d-flex flex-column justify-content-center align-items-center gap-3">
            <fieldset class="d-flex flex-column gap-1 w-100">
                <div class="d-flex w-100">
                    <label asp-for="Email" class="flex-grow-1">Email</label>
                    <span asp-validation-for="Email" class="text-danger"></span>
                    @if (ViewBag.AuthorizeResult != null)
                    {
                        <p class="justify-content-end text-danger">@ViewBag.AuthorizeResult</p>
                    }
                    @if (ViewBag.Credentials != null)
                    {
                        <p class="justify-content-end text-danger">@ViewBag.Credentials</p>
                    }
                </div>

                <input asp-for="Email" id="email" type="email" class="form-control" />
            </fieldset>
            <fieldset class="d-flex flex-column gap-1 w-100">
                <div class="d-flex w-100">
                    <label asp-for="Password" class="flex-grow-1">Password</label>
                    <span asp-validation-for="Password" class="text-danger"></span>
                </div>
                <input asp-for="Password" id="password" type="password" class="form-control" />
            </fieldset>
            <fieldset class="d-flex flex-column gap-2 w-100">
                <button type="submit" class="btn btn-primary">Submit</button>
                <p class="flex-grow-1">You don't have an account? Register <a asp-controller="Authorize" asp-action="Register">here</a></p>
            </fieldset>
        </form>
</section>

HealthManager/Views/Authorize/Register.cshtml
@model HealthManager.Models.DTO.PatientViewModel;
@{
    ViewData["Title"] = "Register";
<style>
        input[type=number]::-webkit-outer-spin-button,
        input[type=number]::-webkit-inner-spin-button {
            -webkit-appearance: none;
            margin: 0;
        }

        /* Para Firefox */
        input[type=number] {
            -moz-appearance: textfield;
        }
</style>
}

<section class="w-100 h-100 d-flex flex-column justify-content-center align-items-center gap-2">
   <form method="post" asp-controller="Authorize" asp-action="Register" class="d-flex flex-column justify-content-center align-items-center gap-2">
        <h2>Register</h2>
        @if(ViewData["ErrorMessage"] != null){
            <span class="text-danger">@ViewData["ErrorMessage"]</span>
        }
        <!--Name & Surname-->
        <fieldset class="w-100 d-flex gap-1">
           <div class="w-100 d-flex flex-column gap-1">
                <div class="w-100 d-flex">
                    <label asp-for="Name" class="flex-grow-1"></label>
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <input type="text" asp-for="Name" class="form-control" />
           </div>
           <div class="w-100 d-flex flex-column gap-1">
                <div class="w-100 d-flex">
                    <label asp-for="Surname" class="flex-grow-1"></label>
                    <span asp-validation-for="Surname" class="text-danger"></span>
                </div>
                <input type="text" asp-for="Surname" class="form-control" />
           </div>
        </fieldset>

        <!--DNI-->
        <fieldset class="w-100 d-flex flex-column gap-1">
            <div class="w-100 d-flex">
                <label asp-for="Dni" class="flex-grow-1">DNI</label>
                <span asp-validation-for="Dni" class="text-danger"></span>
            </div>
            <input type="number" asp-for="Dni" class="form-control" />
        </fieldset>

        <!--Birthdate-->
        <fieldset class="w-100 d-flex flex-column gap-1">
            <div class="w-100 d-flex">
                <label asp-for="Birthdate" class="flex-grow-1">Birth Date</label>
                <span asp-validation-for="Birthdate" class="text-danger"></span>
            </div>
            <input type="date" asp-for="Birthdate" class="form-control" />
        </fieldset>

        <!--Email-->
        <fieldset class="w-100 d-flex flex-column gap-1">
            <div class="w-100 d-flex">
                <label asp-for="Email" class="flex-grow-1"></label>
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <input type="email" asp-for="Email" class="form-control" />
        </fieldset>

        <!--Password & ConfirmPassword-->
        <fieldset class="w-100 d-flex gap-1">
            <div class="w-100 d-flex flex-column gap-1">
                <div class="w-100 d-flex">
                    <label asp-for="Password" class="flex-grow-1"></label>
                    <span asp-validation-for="Password" class="text-danger"></span>
                </div>
                <input type="password" asp-for="Password" class="form-control" />
            </div>
            <div class="w-100 d-flex flex-column gap-1">
                <div class="w-100 d-flex">
                    <label asp-for="ConfirmPassword" class="flex-grow-1">Confirm Password</label>
                    <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                </div>
                <input type="password" asp-for="ConfirmPassword" class="form-control" />
            </div>
        </fieldset>

        <fieldset class="w-100 d-flex gap-1">
            <div class="d-flex flex-column gap-1 w-100">
                <div class="d-flex">
                    <label asp-for="Gender" class="flex-grow-1">Gender</label>
                    <span asp-validation-for="Gender" class="text-danger"></span>
                </div>
                <select asp-for="Gender" class="form-control w-100">
                    <option name="F" value="F">F</option>
                    <option name="m" value="M">M</option>
                </select>
            </div>
            <div class="d-flex flex-column gap-1 w-100">
                <div class="d-flex">
                    <label asp-for="Sex" class="flex-grow-1">Sex</label>
                    <span asp-validation-for="Sex" class="text-danger"></span>
                </div>
                <select asp-for="Sex" class="form-control">
                    <option name="F" value="F">F</option>
                    <option name="m" value="M">M</option>
                </select>
            </div>
        </fieldset>

        <fieldset class="w-100 d-flex flex-column gap-1">
            
        </fieldset>

        <!--Submit-->
        <fieldset class="w-100 d-flex align-items-baseline gap-2">
            <div class="w-25 d-flex flex-grow-1" id="submit-container">
                <button type="submit" class=" btn btn-primary">Submit</button>
            </div>
            <p>You already have an account? Login <a asp-controller="Authorize" asp-action="Login">here</a></p>
        </fieldset>
   </form>
    
</section>